### ISSUE TITLE
not able to install bootloader into system(/) partition missing

### ISSUE THREAD

**Issue by ravi005e** [feren-OS/Bug-Reporting-Center#129]
using latest iso, not able to install bootloader

not able to install bootloader into system(/) partition missing

**Comment by feren** [comment]
If you don't know how to do manual partitioning, it's best to just follow what the steps on the User Guide say to do when installing Feren OS. You'll find the User Guide at https://feren-os-user-guide.readthedocs.io/ where you can then go into the adequate Installation Guide for you.

NOTE: Make sure any hard drive partitions are not mounted (if they are they'll have an eject button on the right of them in Files's left sidebar) otherwise certain installation options will not be available.
