### ISSUE TITLE
3/4-finger gestures

### ISSUE THREAD

**Issue by mcfalld** [feren-OS/Bug-Reporting-Center#250]
**Package Name or Section of Feren OS where this bug resides**
Where does this bug happen? (e.g.: feren-themer-cinnamon) ___

**Describe the bug**
Should be able to set gestures for switching workspaces. 3 finger swipe to the right for next workspace

**Steps to Reproduce**
1. this feature does not exist its not necessary to reproduce

**Expected behavior**
Expect to be able to map gestures to key combinations

**Comment by dominichayesferen** [comment]
This isn't a bug but a feature suggestion. Additionally, since it's for adding a feature to the base Desktop, it should ideally be reported via https://bugs.kde.org/ so that Plasma Developers can all consider adding the requested feature.

Make sure you give your 'bug report' WISHLIST priority to mark it as a suggestion over there.

**Comment by dominichayesferen** [comment]
_Gonna close this for now here, but don't be surprised if it's re-opened later._
