### ISSUE TITLE
A couple of issues

### ISSUE THREAD

**Issue by Harmey1980** [feren-OS/Bug-Reporting-Center#33]
Installed FerenOS yesterday and came across a few bugs/issues out the box.

1.  When installing the Ubuntu Extras via the welcome/update & extras screen.  There wasn't a popup to say Ubuntu Extras was installing after clicking the button.  The only way I knew it was installing was when I tried to close the screen down.

2.  Couldn't access my NAS drive out the box.  Had to install the "gvfs-backend".  I think your still looking into this?

3.  When installing updates via the welcome/update & extra screen I couldn't access the system settings screen.

4.  Can't play media directly from my NAS.  Doesn't matter if that's a MP3, avi, MKV etc.  I have to copy across on to my HD and then it will play.  I've tried a couple of different video & audio programs.

**Comment by feren** [comment]
1. I'll look into it, not sure why it isn't showing the 'Installing' indicator next to the button
2. Yeah, #26 
3. Probably because KDE Frameworks and other things System Settings relies on to run were updating?
4. Not sure as to what would cause that... if you find any ideas as to why let me know, as I can't check myself currently.
