### ISSUE TITLE
Default partitioning doesn't set bootable flag

### ISSUE THREAD

**Issue by ipachip** [feren-OS/Bug-Reporting-Center#39]
**Package Name or Section of Feren OS where this bug resides**
Installation:
 When selecting disk layout (Partitioning)

**Describe the bug**
The installer doesn't set the bootable flag.  After installation "Invalid Partition Table!" is displayed and laptop won't boot.

System: Dell Latitude, E6440
Version: April 2019 snapshot
Installation: DVD

Workaround:
If this happens, boot from cd/dvd, start terminal window
sudo fdisk /dev/sda
Enter 'a' command to toggle bootable flag on partition
Enter 'w' command to write partition table
Enter 'q' command to quit
eject cd/dvd
sudo reboot

**Steps to Reproduce**
1. Clean installation (I used DVD)
1. Select "Erase disk" partitioning 
1. Continue with installation

**Expected behavior**
After installation laptop should boot to new installation.

**Additional context**

**Comment by feren** [comment]
If you're using Calamares 3.2.11 (which July 2019 Snapshot) will be using, this is a known upstream bug in Calamares:
https://github.com/calamares/calamares/issues/1175 (don't get confused by the Milestone, that seems to now be for Calamares 3.2.12 as Calamares 3.2.11 was instead made into a security update due to a security flaw being discovered in 3.2.10)

**Comment by feren** [comment]
This bug was fixed (hopefully) using a downstream script workaround in December 2019 Snapshot.
