### ISSUE TITLE
Chrome Browser no longer syncs or stores passwords in Feren OS Plasma

### ISSUE THREAD

**Issue by draeder** [feren-OS/Bug-Reporting-Center#77]
Chrome Browser no longer syncs or stores passwords in Feren OS Plasma.

**Comment by feren** [comment]
Are you on an installation that has transitioned from Feren OS Classic?

**Comment by draeder** [comment]
@feren Yes. Should I remove and reinstall, perhaps?

**Comment by feren** [comment]
An easy way around would be to delete .config/google-chrome to get back Google Chrome's factory defaults and then open Passwords / Seahorse and delete the Google Chrome passwords entry in there, however, otherwise I'm not sure. I'm guessing Google Chrome expects KWallet in Plasma but since KWallet is disabled as the first time wizard is too confusing IMHO for new users... IDK, I'd expect Google Chrome would remember passwords and sync when they're all added back post-transition.

**Comment by draeder** [comment]
@feren "then open Passwords / Seahorse and delete the Google Chrome passwords entry in there"

I don't know what this means.. where is Passwords / Seahorse? 

The steps up to that point haven't helped. This is a real showstopper for me.

**Comment by feren** [comment]
Seahorse is called "Passwords and Keys" in the applications menu. Don't worry about it, I'm checking myself now.

**Comment by draeder** [comment]
Looks like that was the problem. Seahorse / Passwords and Keys was not installed. Once I installed it, my passwords are now syncing. Shouldn't Seahorse / Passwords and Keys have been installed?

**Comment by feren** [comment]
I had no idea removing seahorse might contribute to this problem. I'll remove it from the package removal list in feren-cinn2plas for now.

**Comment by feren** [comment]
I've always assumed Seahorse is just a GUI wrapper for GNOME Keyring Secrets Management.

**Comment by feren** [comment]
See, my original assumption is that since Plasma usually uses KWallet for password management instead of GNOME Keyring, and Chrome adjusts itself to use KWallet instead if on Plasma, that it's just because it realises it's on Plasma so is doing alternative password management, having first tried KWallet and realising that KWallet is disabled then falling back to either its own password management or a new keyring in GNOME Keyring to store passwords.

**Comment by draeder** [comment]
Either way, I'm glad it's working now! Thanks

**Comment by feren** [comment]
Added a notice and removed the seahorse removal from feren-cinn2plas.
